version: "3.7"

services:
  postgres:
    image: postgres:13.2-alpine
    network_mode: bridge
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=economigos
      - POSTGRES_PASSWORD=economigos@123
      - POSTGRES_DB=economigos_db
    restart: unless-stopped
  # APP***************
  springbootapp:
    image: economigos/economigos-service:latest
    network_mode: bridge
    container_name: springbootapp
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
      - APP_PROFILE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/economigos_db
      - SPRING_DATASOURCE_USERNAME=economigos
      - SPRING_DATASOURCE_PASSWORD=economigos@123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
    restart: unless-stopped
    depends_on:
      - postgres
    links:
      - postgres
  reactapp:
    container_name: reactapp
    image: economigos/economigos-app:latest
    # volumes:
    #     - '.:/app'
    #     - '/app/node_modules'
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    depends_on:
      - springbootapp
    links:
      - springbootapp
volumes:
  postgres-data: